const DATE_VARS = [
  'FECHA_ACTUAL', 'FECHA_DIA', 'FECHA_MES', 'FECHA_MES_NOMBRE',
  'FECHA_ANIO', 'FECHA_LARGA', 'FECHA_HORA',
] as const;

const TRAMITE_VARS = [
  'USUARIO_LOGUEADO', 'ID_TRAMITE', 'CODIGO_TRAMITE',
  'OBSERVACION_TRAMITE', 'NOMBRE_SOLICITANTE',
] as const;

const STUDENT_VARS = [
  'NOMBRE_ESTUDIANTE', 'ESTUDIANTE_DNI', 'ESTUDIANTE_EMAIL', 'ESTUDIANTE_MOBILE',
  'ESTUDIANTE_GENERO', 'ESTUDIANTE_FECHA_NACIMIENTO', 'ESTUDIANTE_EDAD',
  'ESTUDIANTE_DIRECCION', 'ESTUDIANTE_ZONA_RESIDENCIA',
  'ESTUDIANTE_REPRESENTANTE', 'ESTUDIANTE_REPRESENTANTE_MOBILE',
  'ESTUDIANTE_PADRE_NOMBRE', 'ESTUDIANTE_PADRE_MOBILE',
  'ESTUDIANTE_MADRE_NOMBRE', 'ESTUDIANTE_MADRE_MOBILE',
  'ESTUDIANTE_SITUACION_FAMILIAR', 'ESTUDIANTE_VIVE_CON',
] as const;

const PARENT_VARS = [
  'REPRESENTANTE_NOMBRE', 'REPRESENTANTE_DNI', 'REPRESENTANTE_EMAIL',
  'REPRESENTANTE_MOBILE', 'REPRESENTANTE_GENERO', 'REPRESENTANTE_OCUPACION',
  'REPRESENTANTE_NIVEL_EDUCATIVO', 'REPRESENTANTE_DIRECCION',
] as const;

const COURSE_VARS = [
  'CURSO_NOMBRE', 'CURSO_NIVEL', 'CURSO_PARALELO', 'CURSO_JORNADA',
  'CURSO_ESPECIALIDAD', 'CURSO_SUBNIVEL', 'ANIO_LECTIVO', 'CURSO_ESTADO',
  'CURSO_TUTOR', 'CURSO_INSPECTOR', 'CURSO_PSICOLOGO',
] as const;

const INSTITUTION_VARS = [
  'INSTITUCION_NOMBRE', 'INSTITUCION_AMIE', 'INSTITUCION_DISTRITO',
  'INSTITUCION_PROVINCIA', 'INSTITUCION_CANTON', 'INSTITUCION_DIRECCION',
  'INSTITUCION_EMAIL', 'INSTITUCION_CONTACTO',
  'INSTITUCION_AUTORIDAD', 'INSTITUCION_AUTORIDAD_EMAIL', 'INSTITUCION_PERIODO_LECTIVO',
] as const;

export const SYSTEM_VARIABLES = [
  ...DATE_VARS, ...TRAMITE_VARS, ...STUDENT_VARS,
  ...PARENT_VARS, ...COURSE_VARS, ...INSTITUTION_VARS,
] as const;

export type SystemVariable = (typeof SYSTEM_VARIABLES)[number];

export const SYSTEM_VARIABLE_GROUPS: Array<{ label: string; keys: readonly string[] }> = [
  { label: 'Fecha', keys: DATE_VARS },
  { label: 'Trámite', keys: TRAMITE_VARS },
  { label: 'Estudiante', keys: STUDENT_VARS },
  { label: 'Representante', keys: PARENT_VARS },
  { label: 'Curso', keys: COURSE_VARS },
  { label: 'Institución', keys: INSTITUTION_VARS },
];
